version: '3'
services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"

  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - selenium
    command: tail -f /dev/null
